[program:emqx-auth-agent]
command=/opt/emqx_authz_agent/bin/emqx-auth-agent
directory=/opt/emqx_authz_agent
user=emqxauthzagent
autostart=true
autorestart=true
startsecs=3
stopwaitsecs=10
stdout_logfile=/var/log/emqx-auth-agent.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/emqx-auth-agent.err
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=5
environment=RULES_CONFIG="/opt/emqx_authz_agent/config/rules.yaml",PORT="7777",LOG_LEVEL="INFO"
